title: Noncommutative Geometry Seminar @ Texas A&M
logoA: /assets/img/noncommutative_geometry_cover.png
logoB: /assets/img/bloch.gif
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
